kind: Pod
apiVersion: v1
metadata:
  name: mnistinferenceproject-547678596c-b9h9l
  generateName: mnistinferenceproject-547678596c-
  namespace: default
  uid: 72c96dce-2389-4d5f-a1d5-4220fae63e0a
  resourceVersion: '94911'
  creationTimestamp: '2022-11-28T22:32:15Z'
  labels:
    k8s-app: mnistinferenceproject
    pod-template-hash: 547678596c
  annotations:
    cni.projectcalico.org/containerID: d945d74d79ce940a20f137888a8e75a4eab6d9a237fbd11a120e984a2824e168
    cni.projectcalico.org/podIP: 172.17.61.134/32
    cni.projectcalico.org/podIPs: 172.17.61.134/32
    kubectl.kubernetes.io/restartedAt: '2022-11-28T22:32:15Z'
    kubernetes.io/psp: ibm-privileged-psp
  ownerReferences:
    - apiVersion: apps/v1
      kind: ReplicaSet
      name: mnistinferenceproject-547678596c
      uid: c0148748-99b0-4f73-9227-5aeaa592d0ee
      controller: true
      blockOwnerDeletion: true
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2022-11-28T22:32:15Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/restartedAt: {}
          f:generateName: {}
          f:labels:
            .: {}
            f:k8s-app: {}
            f:pod-template-hash: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"c0148748-99b0-4f73-9227-5aeaa592d0ee"}: {}
        f:spec:
          f:containers:
            k:{"name":"mnistinferenceproject"}:
              .: {}
              f:image: {}
              f:imagePullPolicy: {}
              f:name: {}
              f:resources: {}
              f:securityContext:
                .: {}
                f:privileged: {}
              f:terminationMessagePath: {}
              f:terminationMessagePolicy: {}
          f:dnsPolicy: {}
          f:enableServiceLinks: {}
          f:restartPolicy: {}
          f:schedulerName: {}
          f:securityContext: {}
          f:terminationGracePeriodSeconds: {}
    - manager: calico
      operation: Update
      apiVersion: v1
      time: '2022-11-28T22:32:16Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:cni.projectcalico.org/containerID: {}
            f:cni.projectcalico.org/podIP: {}
            f:cni.projectcalico.org/podIPs: {}
      subresource: status
    - manager: kubelet
      operation: Update
      apiVersion: v1
      time: '2022-11-28T22:35:35Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions:
            k:{"type":"ContainersReady"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"Initialized"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"Ready"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
          f:containerStatuses: {}
          f:hostIP: {}
          f:phase: {}
          f:podIP: {}
          f:podIPs:
            .: {}
            k:{"ip":"172.17.61.134"}:
              .: {}
              f:ip: {}
          f:startTime: {}
      subresource: status
spec:
  volumes:
    - name: kube-api-access-2klb9
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
        defaultMode: 420
  containers:
    - name: mnistinferenceproject
      image: waynejinweizhu/mnistinferenceproject
      resources: {}
      volumeMounts:
        - name: kube-api-access-2klb9
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: Always
      securityContext:
        privileged: false
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  serviceAccountName: default
  serviceAccount: default
  nodeName: 10.241.0.4
  securityContext: {}
  schedulerName: default-scheduler
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 600
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 600
  priority: 0
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
status:
  phase: Running
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2022-11-28T22:32:15Z'
    - type: Ready
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2022-11-28T22:35:35Z'
    - type: ContainersReady
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2022-11-28T22:35:35Z'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2022-11-28T22:32:15Z'
  hostIP: 10.241.0.4
  podIP: 172.17.61.134
  podIPs:
    - ip: 172.17.61.134
  startTime: '2022-11-28T22:32:15Z'
  containerStatuses:
    - name: mnistinferenceproject
      state:
        running:
          startedAt: '2022-11-28T22:35:34Z'
      lastState: {}
      ready: true
      restartCount: 0
      image: docker.io/waynejinweizhu/mnistinferenceproject:latest
      imageID: >-
        docker.io/waynejinweizhu/mnistinferenceproject@sha256:1ef77f35f8d1f0e87cbb038d44cf91fa549a8c28f737ab37a27fd0e3073bb30a
      containerID: >-
        containerd://dec61a870aff5243386ee0359b64eff4198f7fa98976d70f6572c1c197cc17a5
      started: true
  qosClass: BestEffort
